kind: Service
apiVersion: v1
metadata:
  name: url-shortner
spec:
  selector:
    app: url-shortner
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortner
spec:
  selector:
    matchLabels:
      app: url-shortner
  replicas: 3
  template:
    metadata:
      labels:
        app: url-shortner
    spec:
      containers:
      - name: url-shortner
        image: neerajs1995/url-shortner
        imagePullPolicy: Never
        ports:
        - containerPort: 5000