kind: Service
apiVersion: v1
metadata:
  name: url-shortner-ngnix
spec:
  type: LoadBalancer
  externalIPs:
  - 145.100.131.111
  selector:
    app: url-shortner-ngnix
  ports:
  - name: http
    port: 8000
    targetPort: 80
  clusterIP: 10.96.154.168
  type: LoadBalancer