kind: Service
apiVersion: v1
metadata:
  name: url-shortner-auth
spec:
  type: LoadBalancer
  externalIPs:
  - 145.100.131.111
  selector:
    app: url-shortner-auth
  ports:
  - name: http
    port: 81
    targetPort: 5000
  clusterIP: 10.100.19.232
  type: LoadBalancer