kind: Service
apiVersion: v1
metadata:
  name: url-shortner
spec:
  type: LoadBalancer
  externalIPs:
  - 145.100.131.111
  selector:
    app: url-shortner
  ports:
  - name: http
    port: 80
    targetPort: 5000
  clusterIP: 10.110.232.189
  type: LoadBalancer