kind: Service
apiVersion: v1
metadata:
  name: url-shortner-ngnix
spec:
  selector:
    app: url-shortner-ngnix
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortner-ngnix
spec:
  selector:
    matchLabels:
      app: url-shortner-ngnix
  replicas: 3
  template:
    metadata:
      labels:
        app: url-shortner-ngnix
    spec:
      containers:
      - name: url-shortner-ngnix
        image: neerajs1995/assignment2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80